version: '3.8'
networks:
  app-network:
services:

  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile.backend
    command: sh -c "python manage.py livereload & python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000" # Django
      - "8888:8888" # Jupyter Notebook
      - "35729:35729" # Livereload
    networks:
      - app-network
    depends_on:
      - db
    env_file:
      - ./backend/.env

  # Not building this currently, as development is hung waiting on backend refactor
  # frontend:
  #   build:
  #     context: .
  #     dockerfile: ./frontend/Dockerfile.frontend
  #   volumes:
  #     - ./frontend:/app
  #     - /app/node_modules
  #   ports:
  #     - "3000:3000"
  #   networks:
  #     - app-network
  #   depends_on:
  #     - backend
  #   env_file:
  #     - ./frontend/.env

  db:
    image: postgres
    environment:
      POSTGRES_DB: nba_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - app-network
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
