# Use the appropriate Node.js base image
FROM node:16 as build

# Set the working directory in the Docker image
WORKDIR /app

# Copy the package.json (and package-lock.json, if available) from your React app
COPY frontend/package*.json /app/

# Install dependencies
RUN npm install

# Copy the rest of your React app
COPY frontend/ /app/

# The command to start your app (e.g., start a development server)
CMD ["npm", "start"]
