# Generated by Django 3.1.2 on 2020-10-25 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ball',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('radius', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Constant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_id', models.IntegerField()),
                ('color', models.CharField(max_length=7)),
                ('name', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.IntegerField()),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.team')),
            ],
        ),
        migrations.CreateModel(
            name='Moment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarter', models.IntegerField()),
                ('game_clock', models.FloatField()),
                ('shot_clock', models.FloatField()),
                ('ball', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.ball')),
                ('players', models.ManyToManyField(to='data.Player')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.IntegerField()),
                ('events', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.event')),
                ('guest_team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guest_team', to='data.team')),
                ('home_team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_team', to='data.team')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='guest_players',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guest_players', to='data.player'),
        ),
        migrations.AddField(
            model_name='event',
            name='home_players',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_players', to='data.player'),
        ),
        migrations.AddField(
            model_name='event',
            name='moments',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.moment'),
        ),
    ]
